name       : poedit
version    : 1.8.8
release    : 1
source     :
    - https://github.com/vslavik/poedit/releases/download/v1.8.8-oss/poedit-1.8.8.tar.gz : f98847410030a06e37b6575a3789b7f2446bed22dcb844d645e3ac1b8eaf7d95
license    : MIT
component  : editor
summary    : Cross-platform gettext catalogs (.po files) editor
description: |
    Cross-platform gettext catalogs (.po files) editor
builddeps  :
    - pkgconfig(gtkspell-2.0)
    - pkgconfig(icu-uc)
    - pkgconfig(liblucene++)
    - libboost-devel
    - wxwidgets-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
