name       : poedit
version    : 2.2.4
release    : 24
source     :
    - https://github.com/vslavik/poedit/releases/download/v2.2.4-oss/poedit-2.2.4.tar.gz : c18ee55fbc03d0a25d8260298a9cc489774140e79fe33ad80fcbc34a97df744a
license    : MIT
component  : editor
summary    : Cross-platform gettext catalogs (.po files) editor
description: |
    This program is a simple translations editor for PO and XLIFF files. It also serves as a GUI frontend to more GNU gettext utilities (win32 version is part of the distribution) and catalogs editor/source code parser. It helps with translating applications into another language.
builddeps  :
    - pkgconfig(gtkspell-2.0)
    - pkgconfig(icu-uc)
    - pkgconfig(liblucene++)
    - libboost-devel
    - wxwidgets-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
