name       : poedit
version    : 2.0.2
release    : 6
source     :
    - https://github.com/vslavik/poedit/releases/download/v2.0.2-oss/poedit-2.0.2.tar.gz : b88bc222d4215344d0eb87dda19aafcc0b2465718c4b556015330beb96f7b402
license    : MIT
component  : editor
summary    : Cross-platform gettext catalogs (.po files) editor
description: |
    Cross-platform gettext catalogs (.po files) editor
builddeps  :
    - pkgconfig(gtkspell-2.0)
    - pkgconfig(icu-uc)
    - pkgconfig(liblucene++)
    - libboost-devel
    - wxwidgets-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
