name       : poedit
version    : 2.0.4
release    : 7
source     :
    - https://github.com/vslavik/poedit/releases/download/v2.0.4-oss/poedit-2.0.4.tar.gz : 3887ab76dfa4607f77be00073277a8c5f060006a014b97d8fe05ebd99aadc61d
license    : MIT
component  : editor
summary    : Cross-platform gettext catalogs (.po files) editor
description: |
    Cross-platform gettext catalogs (.po files) editor
builddeps  :
    - pkgconfig(gtkspell-2.0)
    - pkgconfig(icu-uc)
    - pkgconfig(liblucene++)
    - libboost-devel
    - wxwidgets-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
