name       : poedit
version    : 2.0.9
release    : 19
source     :
    - https://github.com/vslavik/poedit/releases/download/v2.0.9-oss/poedit-2.0.9.tar.gz : 305a97a6a038af0b6b953e6002b100be3d00f499211de4bcb59f32582874d9c0
license    : MIT
component  : editor
summary    : Cross-platform gettext catalogs (.po files) editor
description: |
    Cross-platform gettext catalogs (.po files) editor
builddeps  :
    - pkgconfig(gtkspell-2.0)
    - pkgconfig(icu-uc)
    - pkgconfig(liblucene++)
    - libboost-devel
    - wxwidgets-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
