name       : poedit
version    : 2.0.1
release    : 5
source     :
    - https://github.com/vslavik/poedit/releases/download/v2.0.1-oss/poedit-2.0.1.tar.gz : 8766874175b2221ef670d89b32f0fe900cde3e27e5dcb2c1b6cf6d01e8d56ff3
license    : MIT
component  : editor
summary    : Cross-platform gettext catalogs (.po files) editor
description: |
    Cross-platform gettext catalogs (.po files) editor
builddeps  :
    - pkgconfig(gtkspell-2.0)
    - pkgconfig(icu-uc)
    - pkgconfig(liblucene++)
    - libboost-devel
    - wxwidgets-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
