name       : poedit
version    : 2.0.6
release    : 13
source     :
    - https://github.com/vslavik/poedit/releases/download/v2.0.6-oss/poedit-2.0.6.tar.gz : a9e9feee6d65440008ae3fe24504681fe390cb41233122580f503a677989b1bc
license    : MIT
component  : editor
summary    : Cross-platform gettext catalogs (.po files) editor
description: |
    Cross-platform gettext catalogs (.po files) editor
builddeps  :
    - pkgconfig(gtkspell-2.0)
    - pkgconfig(icu-uc)
    - pkgconfig(liblucene++)
    - libboost-devel
    - wxwidgets-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
