name       : poedit
version    : 1.8.11
release    : 4
source     :
    - https://github.com/vslavik/poedit/releases/download/v1.8.11-oss/poedit-1.8.11.tar.gz : 6f27760ffd67c72164b3a84ad3337fdb4007eb707605a4f15272b5adb1e8a332
license    : MIT
component  : editor
summary    : Cross-platform gettext catalogs (.po files) editor
description: |
    Cross-platform gettext catalogs (.po files) editor
builddeps  :
    - pkgconfig(gtkspell-2.0)
    - pkgconfig(icu-uc)
    - pkgconfig(liblucene++)
    - libboost-devel
    - wxwidgets-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
