name       : poedit
version    : '2.3'
release    : 25
source     :
    - https://github.com/vslavik/poedit/releases/download/v2.3-oss/poedit-2.3.tar.gz : ce6ea0ed5d7e02018aa763513f99aef4e4db8b298f2d272fc39ec3d793613cea
homepage   : https://poedit.net
license    : MIT
component  : editor
summary    : Cross-platform gettext catalogs (.po files) translation editor
description: |
    This program is a simple translations editor for PO and XLIFF files. It also serves as a GUI frontend to more GNU gettext utilities (win32 version is part of the distribution) and catalogs editor/source code parser. It helps with translating applications into another language.
builddeps  :
    - pkgconfig(gtkspell-2.0)
    - pkgconfig(icu-uc)
    - pkgconfig(liblucene++)
    - libboost-devel
    - wxwidgets-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
