name       : poedit
version    : 2.0.8
release    : 18
source     :
    - https://github.com/vslavik/poedit/releases/download/v2.0.8-oss/poedit-2.0.8.tar.gz : 01a12bc28477922e77995350e1f3677701bfbc848af9efcfbd35fbd37c7501c2
license    : MIT
component  : editor
summary    : Cross-platform gettext catalogs (.po files) editor
description: |
    Cross-platform gettext catalogs (.po files) editor
builddeps  :
    - pkgconfig(gtkspell-2.0)
    - pkgconfig(icu-uc)
    - pkgconfig(liblucene++)
    - libboost-devel
    - wxwidgets-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
